export const oc = {
  en: {
    general: "Call Details",
    sched: "Scheduled Order",
    selecteditems: "Selected Items",
    comment: "Add comment",
    comPlaceholder: "Special order, allergies, etc.",
    pay: "Payment method",
    discount: "DISCOUNT",
    prodtotal: "Products",
    delivery: "Delivery",
    disc: "Discount",
    total: "Overall",
    btn: "Confirm order",
  },
  ge: {
    general: "გამოძახების დეტალები",
    sched: "დაგეგმილი გამოძახება",
    selecteditems: "არჩეული პროდუქტი",
    comment: "დაამატე კომენტარი",
    comPlaceholder: "სპეციალური მოთხოვნები, ალერგიები და ა.შ",
    pay: "გადახდის მეთოდი",
    discount: "ფასდაკლება",
    prodtotal: "პროდუქტი",
    delivery: "მიტანა",
    disc: "ფასდაკლება",
    total: "სულ",
    btn: "შეკვეთის დაწყება",
  },
};
